
#include "pal/pal_input.h"

static const char* s_KeyNames[PAL_KEY_MAX] = {

    [PAL_KEY_UNKNOWN] = "UNKNOWN",

    // Letters
    [PAL_KEY_A] = "A",
    [PAL_KEY_B] = "B",
    [PAL_KEY_C] = "C",
    [PAL_KEY_D] = "D",
    [PAL_KEY_E] = "E",
    [PAL_KEY_F] = "F",
    [PAL_KEY_G] = "G",
    [PAL_KEY_H] = "H",
    [PAL_KEY_I] = "I",
    [PAL_KEY_J] = "J",
    [PAL_KEY_K] = "K",
    [PAL_KEY_L] = "L",
    [PAL_KEY_M] = "M",
    [PAL_KEY_N] = "N",
    [PAL_KEY_O] = "O",
    [PAL_KEY_P] = "P",
    [PAL_KEY_Q] = "Q",
    [PAL_KEY_R] = "R",
    [PAL_KEY_S] = "S",
    [PAL_KEY_T] = "T",
    [PAL_KEY_U] = "U",
    [PAL_KEY_V] = "V",
    [PAL_KEY_W] = "W",
    [PAL_KEY_X] = "X",
    [PAL_KEY_Y] = "Y",
    [PAL_KEY_Z] = "Z",

    // Numbers (top row)
    [PAL_KEY_0] = "0",
    [PAL_KEY_1] = "1",
    [PAL_KEY_2] = "2",
    [PAL_KEY_3] = "3",
    [PAL_KEY_4] = "4",
    [PAL_KEY_5] = "5",
    [PAL_KEY_6] = "6",
    [PAL_KEY_7] = "7",
    [PAL_KEY_8] = "8",
    [PAL_KEY_9] = "9",

    // Function keys
    [PAL_KEY_F1] = "F1",
    [PAL_KEY_F2] = "F2",
    [PAL_KEY_F3] = "F3",
    [PAL_KEY_F4] = "F4",
    [PAL_KEY_F5] = "F5",
    [PAL_KEY_F6] = "F6",
    [PAL_KEY_F7] = "F7",
    [PAL_KEY_F8] = "F8",
    [PAL_KEY_F9] = "F9",
    [PAL_KEY_F10] = "F10",
    [PAL_KEY_F11] = "F11",
    [PAL_KEY_F12] = "F12",

    // Control
    [PAL_KEY_ESCAPE] = "Escape",
    [PAL_KEY_ENTER] = "Enter",
    [PAL_KEY_TAB] = "Tab",
    [PAL_KEY_BACKSPACE] = "Backspace",
    [PAL_KEY_SPACE] = "Space",
    [PAL_KEY_CAPSLOCK] = "Capslock",
    [PAL_KEY_NUMLOCK] = "Numlock",
    [PAL_KEY_SCROLLLOCK] = "Scrolllock",
    [PAL_KEY_LSHIFT] = "LeftShift",
    [PAL_KEY_RSHIFT] = "RightShift",
    [PAL_KEY_LCTRL] = "LeftControl",
    [PAL_KEY_RCTRL] = "RightControl",
    [PAL_KEY_LALT] = "LeftAlt",
    [PAL_KEY_RALT] = "RightAlt",

    // Arrows
    [PAL_KEY_LEFT] = "Left",
    [PAL_KEY_RIGHT] = "Right",
    [PAL_KEY_UP] = "Up",
    [PAL_KEY_DOWN] = "Down",

    // Navigation
    
    [PAL_KEY_INSERT] = "Insert",
    [PAL_KEY_DELETE] = "Delete",
    [PAL_KEY_HOME] = "Home",
    [PAL_KEY_END] = "End",
    [PAL_KEY_PAGEUP] = "Pageup",
    [PAL_KEY_PAGEDOWN] = "Pagedown",

    // Keypad
    [PAL_KEY_KP_0] = "Keypad 0",
    [PAL_KEY_KP_1] = "Keypad 1",
    [PAL_KEY_KP_2] = "Keypad 2",
    [PAL_KEY_KP_3] = "Keypad 3",
    [PAL_KEY_KP_4] = "Keypad 4",
    [PAL_KEY_KP_5] = "Keypad 5",
    [PAL_KEY_KP_6] = "Keypad 6",
    [PAL_KEY_KP_7] = "Keypad 7",
    [PAL_KEY_KP_8] = "Keypad 8",
    [PAL_KEY_KP_9] = "Keypad 9",
    [PAL_KEY_KP_ENTER] = "Keypad Enter",
    [PAL_KEY_KP_ADD] = "Keypad Add",
    [PAL_KEY_KP_SUBTRACT] = "Keypad Subtract",
    [PAL_KEY_KP_MULTIPLY] = "Keypad Multiply",
    [PAL_KEY_KP_DIVIDE] = "Keypad Divide",
    [PAL_KEY_KP_DECIMAL] = "Keypad Decimal",
    [PAL_KEY_KP_EQUAL] = "Keypad Equal",

    // Misc
    [PAL_KEY_PRINTSCREEN] = "Printscreen",
    [PAL_KEY_PAUSE] = "Pause",
    [PAL_KEY_MENU] = "Menu",
    [PAL_KEY_APOSTROPHE] = "Apostrophe",
    [PAL_KEY_BACKSLASH] = "Backslash",
    [PAL_KEY_COMMA] = "Comma",
    [PAL_KEY_EQUAL] = "Equal",
    [PAL_KEY_GRAVEACCENT] = "Graveaccent",
    [PAL_KEY_SUBTRACT] = "Subtract",
    [PAL_KEY_PERIOD] = "Period",
    [PAL_KEY_SEMICOLON] = "Semicolon",
    [PAL_KEY_SLASH] = "Slash",
    [PAL_KEY_LBRACKET] = "LeftBracket",
    [PAL_KEY_RBRACKET] = "RightBracket",
    [PAL_KEY_LSUPER] = "LeftSuper",
    [PAL_KEY_RSUPER] = "RightSuper",
};

static const char* s_ScancodeNames[PAL_SCANCODE_MAX] = {

    [PAL_SCANCODE_UNKNOWN] = "UNKNOWN",

    // Letters
    [PAL_SCANCODE_A] = "A",
    [PAL_SCANCODE_B] = "B",
    [PAL_SCANCODE_C] = "C",
    [PAL_SCANCODE_D] = "D",
    [PAL_SCANCODE_E] = "E",
    [PAL_SCANCODE_F] = "F",
    [PAL_SCANCODE_G] = "G",
    [PAL_SCANCODE_H] = "H",
    [PAL_SCANCODE_I] = "I",
    [PAL_SCANCODE_J] = "J",
    [PAL_SCANCODE_K] = "K",
    [PAL_SCANCODE_L] = "L",
    [PAL_SCANCODE_M] = "M",
    [PAL_SCANCODE_N] = "N",
    [PAL_SCANCODE_O] = "O",
    [PAL_SCANCODE_P] = "P",
    [PAL_SCANCODE_Q] = "Q",
    [PAL_SCANCODE_R] = "R",
    [PAL_SCANCODE_S] = "S",
    [PAL_SCANCODE_T] = "T",
    [PAL_SCANCODE_U] = "U",
    [PAL_SCANCODE_V] = "V",
    [PAL_SCANCODE_W] = "W",
    [PAL_SCANCODE_X] = "X",
    [PAL_SCANCODE_Y] = "Y",
    [PAL_SCANCODE_Z] = "Z",

    // Numbers (top row)
    [PAL_SCANCODE_0] = "0",
    [PAL_SCANCODE_1] = "1",
    [PAL_SCANCODE_2] = "2",
    [PAL_SCANCODE_3] = "3",
    [PAL_SCANCODE_4] = "4",
    [PAL_SCANCODE_5] = "5",
    [PAL_SCANCODE_6] = "6",
    [PAL_SCANCODE_7] = "7",
    [PAL_SCANCODE_8] = "8",
    [PAL_SCANCODE_9] = "9",

    // Function keys
    [PAL_SCANCODE_F1] = "F1",
    [PAL_SCANCODE_F2] = "F2",
    [PAL_SCANCODE_F3] = "F3",
    [PAL_SCANCODE_F4] = "F4",
    [PAL_SCANCODE_F5] = "F5",
    [PAL_SCANCODE_F6] = "F6",
    [PAL_SCANCODE_F7] = "F7",
    [PAL_SCANCODE_F8] = "F8",
    [PAL_SCANCODE_F9] = "F9",
    [PAL_SCANCODE_F10] = "F10",
    [PAL_SCANCODE_F11] = "F11",
    [PAL_SCANCODE_F12] = "F12",

    // Control
    [PAL_SCANCODE_ESCAPE] = "Escape",
    [PAL_SCANCODE_ENTER] = "Enter",
    [PAL_SCANCODE_TAB] = "Tab",
    [PAL_SCANCODE_BACKSPACE] = "Backspace",
    [PAL_SCANCODE_SPACE] = "Space",
    [PAL_SCANCODE_CAPSLOCK] = "Capslock",
    [PAL_SCANCODE_NUMLOCK] = "Numlock",
    [PAL_SCANCODE_SCROLLLOCK] = "Scrolllock",
    [PAL_SCANCODE_LSHIFT] = "LeftShift",
    [PAL_SCANCODE_RSHIFT] = "RightShift",
    [PAL_SCANCODE_LCTRL] = "LeftControl",
    [PAL_SCANCODE_RCTRL] = "RightControl",
    [PAL_SCANCODE_LALT] = "LeftAlt",
    [PAL_SCANCODE_RALT] = "RightAlt",

    // Arrows
    [PAL_SCANCODE_LEFT] = "Left",
    [PAL_SCANCODE_RIGHT] = "Right",
    [PAL_SCANCODE_UP] = "Up",
    [PAL_SCANCODE_DOWN] = "Down",

    // Navigation
    [PAL_SCANCODE_INSERT] = "Insert",
    [PAL_SCANCODE_DELETE] = "Delete",
    [PAL_SCANCODE_HOME] = "Home",
    [PAL_SCANCODE_END] = "End",
    [PAL_SCANCODE_PAGEUP] = "Pageup",
    [PAL_SCANCODE_PAGEDOWN] = "Pagedown",

    // Keypad
    [PAL_SCANCODE_KP_0] = "Keypad 0",
    [PAL_SCANCODE_KP_1] = "Keypad 1",
    [PAL_SCANCODE_KP_2] = "Keypad 2",
    [PAL_SCANCODE_KP_3] = "Keypad 3",
    [PAL_SCANCODE_KP_4] = "Keypad 4",
    [PAL_SCANCODE_KP_5] = "Keypad 5",
    [PAL_SCANCODE_KP_6] = "Keypad 6",
    [PAL_SCANCODE_KP_7] = "Keypad 7",
    [PAL_SCANCODE_KP_8] = "Keypad 8",
    [PAL_SCANCODE_KP_9] = "Keypad 9",
    [PAL_SCANCODE_KP_ENTER] = "Keypad Enter",
    [PAL_SCANCODE_KP_ADD] = "Keypad Add",
    [PAL_SCANCODE_KP_SUBTRACT] = "Keypad Subtract",
    [PAL_SCANCODE_KP_MULTIPLY] = "Keypad Multiply",
    [PAL_SCANCODE_KP_DIVIDE] = "Keypad Divide",
    [PAL_SCANCODE_KP_DECIMAL] = "Keypad Decimal",
    [PAL_SCANCODE_KP_EQUAL] = "Keypad Equal",

    // Misc
    [PAL_SCANCODE_PRINTSCREEN] = "Printscreen",
    [PAL_SCANCODE_PAUSE] = "Pause",
    [PAL_SCANCODE_MENU] = "Menu",
    [PAL_SCANCODE_APOSTROPHE] = "Apostrophe",
    [PAL_SCANCODE_BACKSLASH] = "Backslash",
    [PAL_SCANCODE_COMMA] = "Comma",
    [PAL_SCANCODE_EQUAL] = "Equal",
    [PAL_SCANCODE_GRAVEACCENT] = "Graveaccent",
    [PAL_SCANCODE_SUBTRACT] = "Subtract",
    [PAL_SCANCODE_PERIOD] = "Period",
    [PAL_SCANCODE_SEMICOLON] = "Semicolon",
    [PAL_SCANCODE_SLASH] = "Slash",
    [PAL_SCANCODE_LBRACKET] = "LeftBracket",
    [PAL_SCANCODE_RBRACKET] = "RightBracket",
    [PAL_SCANCODE_LSUPER] = "LeftSuper",
    [PAL_SCANCODE_RSUPER] = "RightSuper"
};