name: Build and Test Debug

on:
  workflow_dispatch:
  pull_request:
  push:
    # branches: [ master ]

jobs:
  build-and-test:
    timeout-minutes: 4
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-lastest
            compiler: gcc
            toolset: gcc

          - os: ubuntu-lastest
            compiler: clang
            toolset: gcc

          # Windows
          - os: windows-lastest
            compiler: msvc
            toolset: msvc

          - os: windows-lastest
            compiler: gcc
            toolset: gcc

          - os: windows-lastest
            compiler: clang
            toolset: gcc

          - os: windows-lastest
            compiler: clang
            toolset: msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configuration
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Compiler: ${{ matrix.compiler }}"
          echo "Toolset: ${{ matrix.toolset }}"
          echo "Configuration: Release"






