
name: Check Internal Documentation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  check-internal-docs:
    name: check-internal-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Run Doxygen
        run: scripts/check-internal-docs.py