
name: Clang Tidy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  clang-tidy-linux:
    name: clang-tidy-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libvulkan-dev

      - name: Install Clang Tidy
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-tidy-22
          sudo ln -sf /usr/bin/clang-tidy-22 /usr/bin/clang-tidy

      - name: Generate
        run: ./premake/premake5 gmake --override

      - name: Make Files Writable
        run: chmod -R u+w .

      - name: Run Clang Tidy
        run: python3 scripts/run-clang-tidy.py

  clang-tidy-windows:
    name: clang-tidy-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: microsoft/setup-msbuild@v3

      - name: Download Vulkan SDK
        shell: pwsh
        run: curl.exe -L -o vulkan-sdk.exe https://sdk.lunarg.com/sdk/download/1.4.357.0/windows/vulkan_sdk.exe

      - name: Install Vulkan SDK
        shell: pwsh
        run: .\vulkan-sdk.exe --accept-licenses --default-answer --confirm-command install

      - name: Install Clang Tidy
        shell: pwsh
        run: choco install llvm --version=22.1.0 -y

      - name: Setup Vulkan Environment
        run: |
          "VULKAN_SDK=C:\VulkanSDK\1.4.357.0" >> $env:GITHUB_ENV

      - name: Generate
        shell: cmd
        run: premake\premake5.exe vs2022 --override

      - name: Run Clang Tidy
        run: python3.exe scripts/run-clang-tidy.py