
name: Clang Format Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Clang Format
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22

      - name: Make Files Writable
        run: chmod -R u+w .

      - name: Check Format
        run: |
          files=$(git ls-files '*.c' '*.cpp' '*.h' '*.hpp')
          if [ -n "$files" ]; then
            clang-format-22 --dry-run --Werror $files
          fi
