
name: Main
on:
  pull_request:
  push:
    #TODO: remove comment branches: [ master ]

jobs:
  main-linux:
    name: main-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libvulkan-dev

      - name: Generate
        run: ./premake/premake5 gmake --ci

      - name: Build
        run: make -j config=release

      - name: Run
        run: ./bin/Release/tests

  main-windows:
    name: main-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: microsoft/setup-msbuild@v3

      - name: Download Vulkan SDK
        shell: pwsh
        run: |
          curl.exe -L -o vulkan-sdk.exe https://sdk.lunarg.com/sdk/download/1.4.357.0/windows/vulkan_sdk.exe

      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          Start-Process .\vulkan-sdk.exe -ArgumentList "/S" -Wait

      - name: Remove Vulkan SDK
        shell: pwsh
        run: |
          Remove-Item .\vulkan-sdk.exe

      - name: Generate
        shell: cmd
        run: premake\premake5.exe vs2022 --ci

      - name: Build
        shell: cmd
        run: msbuild PALWorkspace.sln /m /p:Configuration=Release

      - name: Run
        shell: cmd
        run: bin\Release\tests.exe