
name: Main
on:
  pull_request:
  push:
    #TODO: remove comment branches: [ master ]

jobs:
  main-linux:
    name: main-linux
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Configuration
        run: |
          echo "Linux"

  main-windows:
    name: main-windows
    runs-on: windows-latest
    timeout-minutes: 4

    steps:
      - name: Configuration
        run: |
          echo "Windows"